apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  cockroach.server: | # you may select any name here, but it must end with the .server file extension
    ukwest.svc.cluster.local:53 {
        errors
        cache 30
        forward . 10.2.1.91 {
        }
    }
    northeurope.svc.cluster.local:53 {
        errors
        cache 30
        forward . 10.3.1.91
    }